[project]
name = "circula-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=37.0.2",
    "playwright>=1.51.0",
    "pytest>=8.3.5",
]
